### ISSUE TITLE
Webpack 4 Support? DeprecationWarning: Tapable.plugin & Chunk.mapModules

### ISSUE THREAD

**Issue by joyfulelement** [dsebastien/webpack-sha-hash#9]
#### Question
Is this plugin intend to support Webpack 4?

#### What is the current behavior?
When upgrading to webpack 4 and with the node tracing turned on (`process.traceDeprecation = true;` in `webpack.config.js`), by running the `webpack-dev-server --mode development`, the following `DeprecationWarning` with stack trace is shown.

```
(node:32184) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackSHAHash.apply (C:\app\node_modules\webpack-sha-hash\dist\webpack_sha_hash.js:85:22)
    at webpack (C:\app\node_modules\webpack\lib\webpack.js:37:12)
    at options.map.options (C:\app\node_modules\webpack\lib\webpack.js:28:55)
    at Array.map (<anonymous>)
    at webpack (C:\app\node_modules\webpack\lib\webpack.js:28:40)
    at startDevServer (C:\app\node_modules\webpack-dev-server\bin\webpack-dev-server.js:379:16)
    at portfinder.getPort (C:\app\node_modules\webpack-dev-server\bin\webpack-dev-server.js:369:5)
    at C:\app\node_modules\portfinder\lib\portfinder.js:160:14
    at C:\app\node_modules\async\lib\async.js:52:16
    at C:\app\node_modules\async\lib\async.js:269:32

(node:32184) DeprecationWarning: Chunk.mapModules: Use Array.from(chunk.modulesIterable, fn) instead
    at C:\app\node_modules\webpack-sha-hash\dist\webpack_sha_hash.js:87:65
    at SyncHook.eval [as call] (eval at create (C:\app\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (C:\app\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.createHash (C:\app\node_modules\webpack\lib\Compilation.js:1705:25)
    at hooks.optimizeTree.callAsync.err (C:\app\node_modules\webpack\lib\Compilation.js:933:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\app\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\app\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\app\node_modules\webpack\lib\Compilation.js:890:27)
    at hooks.make.callAsync.err (C:\app\node_modules\webpack\lib\Compiler.js:481:17)
    at _err0 (eval at create (C:\app\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
```

#### What is the expected behaviour?
Since this is a deprecation warning, if the plug-in is not intended to be used with Webpack 4, they can be ignored. On the other hand, on webpack's documentation, [output.hashFunction](https://webpack.js.org/configuration/output/#output-hashfunction) property seems configurable and perhaps using it to define a alternative hash function without using `webpack-sha-hash` plugin would the official way to go with Webpack 4? It would be grateful if some clarity can be provided in the readme regards to Webpack 4 support and the expected deprecation warnings.

#### Dependencies/Tool Lineup
```
"webpack": "4.6.0",
"webpack-cli": "2.0.15",
"webpack-dev-server": "3.1.3",
"webpack-sha-hash": "2.0.0",
Node v8.9.1
Windows 10
```

**Comment by dsebastien** [comment]
Indeed Webpack 4 support would be nice to have, unfortunately I don't have much time to maintain this project at the moment.

I couldn't take a look yet at what Webpack 4 brings to the table. If this plugin then becomes obsolete, then that would be great :)
